### ISSUE TITLE
Add a 'Quit' or 'Exit' menu item to the 'File' menu

### ISSUE THREAD

**Issue by evanspa** [DaveRead/BasicQuery#1]
A nit: it would be nice to have a 'Quit' or 'Exit' menu item added to the 'File' menu.  I know I can quit just fine with the red-x or cmd-Q (on Mac), but I will habitually click the 'File' menu to quit the app if my hand is already on the mouse.

**Comment by DaveRead** [comment]
By your command! :) See version 02.00.07 - just released. Hope you are well.
